### ISSUE TITLE
How to run 

### ISSUE THREAD

**Issue by usmann2023** [ikromin/jphotoframe#4]
Hi 
I am having problem in running code. i cannot find jphotofram.jar file any where
![Capture](https://user-images.githubusercontent.com/44524122/69910256-78f77a80-1408-11ea-89f6-87d865cfa480.PNG)

**Comment by ikromin** [comment]
The README.md specifies this...

Building
Use Maven to build.
mvn clean package

I am not providing support for other build systems or IDEs.
